#version: '3'

services:
  tidb:
    image: pingcap/tidb:latest
#    container_name: tidb-server
    ports:
      - "4000:4000"
      - "10080:10080"
    environment:
      - "TZ=UTC"
    networks:
      - tidb-net

  pd:
    image: pingcap/pd:latest
#    container_name: pd-server
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - "TZ=UTC"
    networks:
      - tidb-net

  tikv:
    image: pingcap/tikv:latest
#    container_name: tikv-server
    ports:
      - "20160:20160"
      - "20180:20180"
    environment:
      - "TZ=UTC"
    networks:
      - tidb-net
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - tidb-net  
networks:
  tidb-net:
    driver: bridge